/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        black: "#1A1A1A",
        tomato: "#EA4913",
        cerulean: "#0565BB",
        whiteTwo: "#EEEEEE",
        kelleyGreen: "#00833F",
        lavender: "#C6B8F5",
        darkBrown: "#110E03",
        brightOrangeTwo: "#FF5500",
        mango: "#FFB225",
        tomatoTwo: "#E84C33",
        bluish: "#2584B3",
        sand: "#DABB5E",
        copper: "#C73C27",
        mangoTwo: "#FFB227",
        eggshell: "#FFFBD8",
        tomatoThree: "#E0412A",
        lightGrey: "#CED1C8",
        pinkishGrey: "#D4C4AB",
        cloudyBlue: "#B1D1CF",
        lightGreyTwo: "#D8DAD7",
        midBlue: "#245FC5",
        greyish: "#A9A9A9",
        sunYellow: "#FCD32A",
        dark: "#1C2027",
        whiteThree: "#F4F4F4",
        brownishGrey: "#666666",
        pumpkinOrange: "#FA7B26",
        pinkishGreyTwo: "#CCC8C6",
        whiteFour: "#F1F1F1",
        darkmaroon: "#020001",
        blackThree: "#222222",
        clearBlue: "#157EFF",
        goldenrod: "#FCCB05",
        blackTwo: "#111111",
        white: "#FFFFFF",
        brightOrange: "#F96400",
      },
      maxWidth: {
        xxl: "1920px",
      },
      width: {
        xxl: "1920px",
      },
      screens: {
        xxs: "320px",
        xs: "480px",
        xxl: "1920px",
      },
    },
  },
  plugins: [require("tailwindcss"), require("autoprefixer")],
};
